# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_complexmodule')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_complexmodule')
    _complexmodule = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_complexmodule', [dirname(__file__)])
        except ImportError:
            import _complexmodule
            return _complexmodule
        try:
            _mod = imp.load_module('_complexmodule', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _complexmodule = swig_import_helper()
    del swig_import_helper
else:
    import _complexmodule
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _complexmodule.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self) -> "PyObject *":
        return _complexmodule.SwigPyIterator_value(self)

    def incr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _complexmodule.SwigPyIterator_incr(self, n)

    def decr(self, n: 'size_t'=1) -> "swig::SwigPyIterator *":
        return _complexmodule.SwigPyIterator_decr(self, n)

    def distance(self, x: 'SwigPyIterator') -> "ptrdiff_t":
        return _complexmodule.SwigPyIterator_distance(self, x)

    def equal(self, x: 'SwigPyIterator') -> "bool":
        return _complexmodule.SwigPyIterator_equal(self, x)

    def copy(self) -> "swig::SwigPyIterator *":
        return _complexmodule.SwigPyIterator_copy(self)

    def next(self) -> "PyObject *":
        return _complexmodule.SwigPyIterator_next(self)

    def __next__(self) -> "PyObject *":
        return _complexmodule.SwigPyIterator___next__(self)

    def previous(self) -> "PyObject *":
        return _complexmodule.SwigPyIterator_previous(self)

    def advance(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _complexmodule.SwigPyIterator_advance(self, n)

    def __eq__(self, x: 'SwigPyIterator') -> "bool":
        return _complexmodule.SwigPyIterator___eq__(self, x)

    def __ne__(self, x: 'SwigPyIterator') -> "bool":
        return _complexmodule.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _complexmodule.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator &":
        return _complexmodule.SwigPyIterator___isub__(self, n)

    def __add__(self, n: 'ptrdiff_t') -> "swig::SwigPyIterator *":
        return _complexmodule.SwigPyIterator___add__(self, n)

    def __sub__(self, *args) -> "ptrdiff_t":
        return _complexmodule.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _complexmodule.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Complex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Complex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Complex, name)
    __swig_setmethods__["x"] = _complexmodule.Complex_x_set
    __swig_getmethods__["x"] = _complexmodule.Complex_x_get
    if _newclass:
        x = _swig_property(_complexmodule.Complex_x_get, _complexmodule.Complex_x_set)
    __swig_setmethods__["y"] = _complexmodule.Complex_y_set
    __swig_getmethods__["y"] = _complexmodule.Complex_y_get
    if _newclass:
        y = _swig_property(_complexmodule.Complex_y_get, _complexmodule.Complex_y_set)

    def getX(self) -> "int":
        return _complexmodule.Complex_getX(self)

    def getY(self) -> "int":
        return _complexmodule.Complex_getY(self)

    def __init__(self, x_: 'int'=0, y_: 'int'=0):
        this = _complexmodule.new_Complex(x_, y_)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def __add__(self, rhs: 'Complex') -> "Complex":
        return _complexmodule.Complex___add__(self, rhs)

    def __sub__(self, rhs: 'Complex') -> "Complex":
        return _complexmodule.Complex___sub__(self, rhs)

    def toString(self) -> "std::string":
        return _complexmodule.Complex_toString(self)

    def __repr__(self) -> "std::string":
        return _complexmodule.Complex___repr__(self)
    __swig_destroy__ = _complexmodule.delete_Complex
    __del__ = lambda self: None
Complex_swigregister = _complexmodule.Complex_swigregister
Complex_swigregister(Complex)

# This file is compatible with both classic and new-style classes.


